spring.application.name=ai-notes-manager
spring.datasource.url=jdbc:mysql://localhost:3306/ainotesdb
spring.datasource.username=root
spring.datasource.password=Chess2211##
spring.jpa.hibernate.ddl-auto=update